# 服务端口号，默认80
server:
  port: 5188
spring:
  # 服务名称
  application:
    name: netty-server
  datasource:
    druid:
      url: jdbc:mysql://125.77.202.162:20035/ffswllp_ll_sw?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true&connectTimeout=30000&socketTimeout=60000
      username: ffswllp
      password: swllp0328
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1 # 地址
    port: 6379 # 端口
    database: 0 # 数据库索引
    password: 123456 # 密码，建议生产环境开启

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml

# 日志文件配置
logging:
  level:
    # 配置自己写的 MyBatis Mapper 打印日志
    com.fourfaith.dal.mysql: debug

thingsboard:
  netty:
    address: 27.154.58.226
    udp:
      port: 9145
    tcp:
      port: 5200

mqtt:
  host: tcp://27.154.58.226:25138
  topic: fourfaith/device/rpc/request/+
  username: test1
  password: 1


